apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/vfarcic/devops-paradox.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        ingress:
          host: devops-paradox.16.0.45.162.xip.io # i bet this is wrong
        version: v3
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true